# Generated by Django 5.0.6 on 2024-06-03 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_personuser_username_alter_personuser_email_and_more'),
    ]

    operations = [
     
    ]
