# Generated by Django 5.0.6 on 2024-06-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='personuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='personuser',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='personuser',
            name='username',
        ),
        migrations.AddField(
            model_name='personuser',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Designates whether the user has all permissions without explicitly assigning them.'),
        ),
        migrations.AlterField(
            model_name='personuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='personuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='personuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='personuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='+', related_query_name='%(app_label)s_%(class)s', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='personuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='personuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='personuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='+', related_query_name='%(app_label)s_%(class)s', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
