# Generated by Django 5.0.6 on 2024-06-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_personuser_options_alter_personuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
